print()
title=input('Title: ')
year=input('Year: ')
name=title.lower().replace(' ','-')+'-'+year
direct=input('Director: ')
star1=input('Star 1: ')
star2=input('Star 2: ')
star3=input('Star 3: ')
descript=input('Description: ')
def firstUpper(title):
        str = title.title()
        str = str.replace('And ','and ')
        str = str.replace('The ','the ')
        str = str.replace('Of ','of ')
        str = str.replace('In ','in ')
        str = str.replace('At ','at ')
        str = str.replace('By ','by ')
        str = str[0].upper() + str[slice(1,len(str))]
        return str;
print()
print(name)
print()
print('<!DOCTYPE html>\n<html lang="pl-PL">\n    <head>\n        <title>VERTE.IO</title>\n        <meta charset="utf-8"/>\n        <meta name="author" content="xaamus"/>\n        <meta name="viewport" content="width=device-width, initial-scale=1.0">\n        <link href="/styles/styles.css" rel="stylesheet">\n        <link href="/styles/thdark.css" rel="stylesheet" id="linkCSS">\n        <script src="/scripts/scripts.js" async defer></script>\n        <script src="/scripts/genvideoinfo.js" async defer></script>\n        <script src="/scripts/video/video.js" async defer></script>\n        <script src="/scripts/video/'+name+'.js" async defer></script>\n        <link rel="preconnect" href="https://fonts.googleapis.com">\n        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,700,0,0" rel="stylesheet">\n    </head>\n    <body>\n        <header>\n            <div id="headerCent">\n				<div id="navTitle">\n					<a href="/VERTE.IO/index.html" id="navTitleEle">VERTE.IO</a>\n				</div>\n				<div id="navSearch">\n					<form action id="navSearchForm">\n						<input id="navSearchEle" type="text" title="search" placeholder="videos">\n						<input id="navSearchSum" type="submit" title="submit" value="submit" hidden>\n					</form>\n				</div>\n				<div id="navTheme">\n					<p id="navThemeEle">DARK</p>\n				</div>\n            </div>\n        </div>\n        <div id="main">\n            <div id="mainCent">\n                <div id="videoAsideL">\n                    <div id="videoInfo">')
print('                        <div id="videoPicOut"><img id="videoPic" src="/media/video/'+name+'.webp"></div>')
print('                        <div id="videoDet">')
print('                            <p><span>'+firstUpper(title)+' ('+year+')</span></p>')
print('                            <p><span>Stars: </span>'+star1.title()+', '+star2.title()+', '+star3.title()+'</p>')
print('                            <p><span>Director: </span>'+direct.title()+'</p>')
print('                            <p>'+descript+'</p>')
print('                        </div>')
print('                    </div>\n                </div>\n                <div id="videoAsideR">\n                    <div id="videoWatch">\n                        <div id="iframeOut">                            <iframe src="" id="iframeId" title="video"></iframe>                        </div>\n                        <p id="videoWatchTitle"></p>\n                    </div>\n                </div>\n            </div>\n			<div id="scroll"></div>\n        </div>\n        <footer>\n            <div id="footerCent">\n                <span id="footerEle">xaamus :: 2021 - 2023</span>\n            </div>\n        </div>\n        <a href="#" id="goUp" class="material-symbols-rounded">arrow_upward</a>\n    </body>\n</html>')
print()